basic:
  has_velo: True       # CenterPoint detector has velo info
  LiDAR_interval: 0.5  # the interval between two adjacent frames of the LiDAR scan, NuScenes: 2HZ
  CLASS_NUM: 7         # number of tracking category, NuScenes: 7
  # CLASS_LABEL: 'bicycle': 0, 'bus': 1, 'car': 2, 'motorcycle': 3, 'pedestrian': 4, 'trailer': 5, 'truck': 6

preprocessing:
  SF_thre: {0: 0.14, 3: 0.12, 1: 0, 2: 0.16, 5: 0.1, 6: 0, 4: 0.16}
  NMS_thre: 0.08
  NMS_type: blend_nms  # blend_nms, no_blend_nms, blend_soft_nms
  NMS_metric: iou_bev  # iou_bev, iou_3d, giou_bev, giou_3d, d_eucl

association:
  category_metrics: {1: 'giou_bev', 0: 'giou_3d', 2: 'giou_3d', 3: 'giou_3d', 4: 'giou_3d', 5: 'giou_3d', 6: 'giou_3d'}
  second_metric: 'giou_bev'
  two_stage: True  # Whether to use two-stage data association
  first_thre: {1: 1.5, 0: 1.5, 2: 1.5, 3: 1.5, 4: 1.5, 5: 1.5, 6: 1.5}  # category-specific one-stage thresholds
  second_thre: {1: 1, 0: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1}  # two-stage thresholds
  algorithm : 'Hungarian'  # Greedy, Hungarian, Mutual Nearest Neighbor(MNN)

motion_model:
  # two kalman filter, LinearKalmanFilter, ExtendKalmanFilter
  filter: {1: 'ExtendKalmanFilter', 0: 'ExtendKalmanFilter', 2: 'ExtendKalmanFilter', 3: 'ExtendKalmanFilter', 4: 'ExtendKalmanFilter', 5: 'ExtendKalmanFilter', 6: 'ExtendKalmanFilter'}
  # five motion model, Linear Model: CV, CA, Non-Linear: CTRA, CTRV, BICYCLE
  # note the consistency of the linear relationship between the model and the filter
  model: {1: 'CTRA', 0: 'BICYCLE', 2: 'CTRA', 3: 'BICYCLE', 4: 'CTRA', 5: 'CTRA', 6: 'CTRA'}

life_cycle:
  max_age: {1: 10, 0: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10}
  min_hit: {1: 1, 0: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1}

output:
  punish_num: 1  # The maximum number of predicted frames to write to the output file
  post_nms: false # whether to use post-nms, this feature is used to reduce FP prediction
  NMS_thre: 0.08
  NMS_type: blend_nms  # blend_nms, no_blend_nms, blend_soft_nms
  NMS_metric: iou_bev  # iou_bev, iou_3d, giou_bev, giou_3d, d_eucl

debug:
  is_debug: true # Whether to debug the code

